<a href="https://colab.research.google.com/github/Farhan124682727265226/pandas-and-numpy/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

a=np.arange(4,10)

s=pd.Series(a)

print(s)
# print(s.ndim)
# print(s.size)
# print(s.shape)

print(s.head()) # intial row

print(s.tail()) # last row by defualt get 5 row

0    4
1    5
2    6
3    7
4    8
5    9
dtype: int64
0    4
1    5
2    6
3    7
4    8
dtype: int64
1    5
2    6
3    7
4    8
5    9
dtype: int64

In [ ]:
#create two series

a=pd.Series([4,5,6,7,8])
b=pd.Series([5,4,3,6,7])

print(a)
print(b)

d=pd.concat([a,b],ignore_index=True) #concat - combine two series
print(d)

0    4
1    5
2    6
3    7
4    8
dtype: int64
0    5
1    4
2    3
3    6
4    7
dtype: int64
0    4
1    5
2    6
3    7
4    8
5    5
6    4
7    3
8    6
9    7
dtype: int64

In [ ]:
#series addition

# e=a.add(b)
# print(e)

# q=a.sub(b)
# print(q)

w=a.mul(b)
print(w)

# r=a.div(b)
# print(r)

0    20
1    20
2    18
3    42
4    56
dtype: int64

In [ ]:
z=pd.Series([3,4,5,6],index=["a","b","c","d"]) # to get custom index
print(z)

a    3
b    4
c    5
d    6
dtype: int64

In [ ]:
#dictionary

d={"id":1,"age":66,"class":"ds"}
z=pd.Series(d)
print(z)

id        1
age      66
class    ds
dtype: object

In [ ]:
z=pd.Series(4,index=[1,2,3,4])
z

1    4
2    4
3    4
4    4
dtype: int64

In [ ]:
z=pd.Series([1,2,3,4,5,6,7])
print(z)
z[3]
print(z[1:3])
z[[6,1,5]]   #to get multiple index [[]]

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64
1    2
2    3
dtype: int64

6    7
1    2
5    6
dtype: int64

In [ ]:
#data frame (row column)

#creating dat frame from list

l=[1,2,3,4,5]

df=pd.DataFrame(l)
print(df)
# df.shape
# df.size
# df.ndim

   0
0  1
1  2
2  3
3  4
4  5

In [ ]:
#create data frame from nested list

l=[["apple",102],["orange",48],["grapes",56]]

df=pd.DataFrame(l,columns=["fruits","price"])
df

   fruits  price
0   apple    102
1  orange     48
2  grapes     56

In [ ]:
#create a data frame with id name and location and add 4 rows

l=[[1,"farhan","tvm"],[2,"manu","kochi"],[3,"anu","tvm"],[4,"abu","calicut"]]

df=pd.DataFrame(l,columns=["id","name","location"])
df

print(df.tail(1))
df.head(1)

   id name location
3   4  abu  calicut

   id    name location
0   1  farhan      tvm

In [ ]:
#using dictionary and list

d={"id":[1,2,3,4],"name":["john","mon","ramu","abu"],"age":[3,4,5,6]}
df=pd.DataFrame(d)
df

   id  name  age
0   1  john    3
1   2   mon    4
2   3  ramu    5
3   4   abu    6

In [2]:

import pandas as pd

d={"id":[1,2,3,4,5],"name":["john","farhan","rihan","manu","anu"],"age":[10,20,30,22,11],"salary":[1000,22220,1000,30000,1020],"profession":["cs","ece","hr","eee","mech"]}

df=pd.DataFrame(d)
df["gender"]=["male","male","male","male","female"]   # add extra a column
df

   id    name  age  salary profession  gender
0   1    john   10    1000         cs    male
1   2  farhan   20   22220        ece    male
2   3   rihan   30    1000         hr    male
3   4    manu   22   30000        eee    male
4   5     anu   11    1020       mech  female